[phases.setup]
nixPkgs = ["python39", "gcc", "postgresql"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmd = "python run_migrations.py && python telegram_bot_with_graphs.py" 